#!/usr/bin/env bash
# gen-splash.sh — generate src/splash.cyr (the startup ibis) from thoth_v1.tiff.
#
# thoth_v1.tiff is the SOURCE OF TRUTH for the mark: a 4400x2400 line-art ibis (Thoth) under the
# sun disk, inside a ring. The binary can't read the image at run time, so this renders it to
# ASCII density art at a few column widths and embeds the rows into source — splash_row(w, i) —
# the way gen-version.sh embeds VERSION. Re-run whenever the TIFF (or the ramp / widths below)
# changes; the generated src/splash.cyr IS committed so a raw `cyrius build` still has it.
#
# Pipeline (ImageMagick 7 + awk, nothing else):
#   1. flatten the alpha onto white, threshold -> pure ink
#   2. drop the ring: of the ink's connected components, the one with the largest bounding box
#      (it encloses everything else), then trim to the figure
#   3. per width W: box-average to W x R cells (R keeps the figure's aspect at a 1:2 cell), gamma
#      the coverage, map each cell to the 10-step ramp " .:-=+*#%@"
#
# The ramp's four shades (@%# / *+= / -: / .) are what splash_tier() reports, so a painter can
# colour by role (accent / accent-dim / muted / faint) without knowing the ramp.
set -euo pipefail
cd "$(dirname "$0")/.."

SRC="${1:-thoth_v1.tiff}"
OUT="src/splash.cyr"
WIDTHS="${SPLASH_WIDTHS:-32 40 48 56}"
RAMP=' .:-=+*#%@'
GAMMA="${SPLASH_GAMMA:-0.6}"

command -v magick >/dev/null || { echo "gen-splash: ImageMagick 7 (magick) is required" >&2; exit 1; }
[ -f "$SRC" ] || { echo "gen-splash: no such image: $SRC" >&2; exit 1; }

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

# 1. ink: alpha onto white, grayscale, hard threshold. Ink is BLACK here; morphology below wants it white.
magick "$SRC" -background white -alpha remove -alpha off -colorspace gray -threshold 50% "$tmp/ink.png"

# 2. the ring = the ink component (gray(255) after -negate) with the largest bounding box.
ring="$(magick "$tmp/ink.png" -negate \
          -define connected-components:verbose=true \
          -define connected-components:area-threshold=200 \
          -connected-components 8 null: 2>&1 \
        | awk '/gray\(255\)/ { split($2, g, /[x+]/); a = g[1] * g[2]; if (a > best) { best = a; id = $1 } }
               END { sub(/:$/, "", id); print id }')"
[ -n "$ring" ] || { echo "gen-splash: could not find the ring component" >&2; exit 1; }
magick "$tmp/ink.png" -negate \
  -define connected-components:area-threshold=200 \
  -define connected-components:mean-color=true \
  -define connected-components:remove-ids="$ring" \
  -connected-components 8 -negate -trim +repage "$tmp/fig.png"
FW="$(magick "$tmp/fig.png" -format '%w' info:)"
FH="$(magick "$tmp/fig.png" -format '%h' info:)"

# 3. per width: coverage -> ramp. P2 (ASCII) PGM so awk reads the cell values straight off the stream.
render() {   # render W  -> rows on stdout (trailing spaces stripped)
    local W="$1"
    local R
    R="$(awk -v fw="$FW" -v fh="$FH" -v w="$W" 'BEGIN { printf "%d", (fh / fw) * w / 2 + 0.5 }')"
    magick "$tmp/fig.png" -negate -filter box -resize "${W}x${R}!" -depth 8 -compress none pgm:- \
    | awk -v W="$W" -v R="$R" -v ramp="$RAMP" -v gamma="$GAMMA" '
        /^#/ { next }
        { for (i = 1; i <= NF; i++) { tok[n++] = $i } }
        END {
            # tokens: P2, width, height, maxval, then W*R values row-major
            base = 4; maxv = tok[3]; steps = length(ramp) - 1
            for (r = 0; r < R; r++) {
                line = ""
                for (c = 0; c < W; c++) {
                    v = tok[base + r * W + c] / maxv
                    if (v > 0) { v = v ^ gamma }
                    k = int(v * steps + 0.5)
                    line = line substr(ramp, k + 1, 1)
                }
                sub(/ +$/, "", line)
                print line
            }
        }'
}

# 4. emit src/splash.cyr
{
    echo "# thoth — the startup ibis: thoth_v1.tiff (ring removed) as ASCII density art. GENERATED by"
    echo "# scripts/gen-splash.sh — DO NOT EDIT BY HAND; the TIFF is the source of truth (re-run the script)."
    echo "#"
    echo "# Ramp \"$RAMP\" (light -> dense), gamma $GAMMA, box-averaged from the ${FW}x${FH} figure at a 1:2 cell."
    echo "# Rows carry no trailing spaces and no escapes (7-bit ASCII only — safe for the GUI's CP437 raster and"
    echo "# dumb terminals alike). splash_tier(ch) folds a ramp byte to a 0..3 shade (0 = densest, -1 = paint"
    echo "# nothing) so a painter can colour by role without knowing the ramp."
    echo "fn splash_widths() { return $(echo $WIDTHS | wc -w); }"
    k=0
    printf 'fn splash_width(k) {'
    for W in $WIDTHS; do printf ' if (k == %d) { return %d; }' "$k" "$W"; k=$((k + 1)); done
    echo ' return 0; }'
    for W in $WIDTHS; do render "$W" > "$tmp/rows.$W"; done
    printf 'fn splash_rows(w) {'
    for W in $WIDTHS; do printf ' if (w == %d) { return %d; }' "$W" "$(wc -l < "$tmp/rows.$W")"; done
    echo ' return 0; }'
    printf 'fn splash_row(w, i) {'
    for W in $WIDTHS; do printf ' if (w == %d) { return _splash_%d(i); }' "$W" "$W"; done
    echo ' return 0; }'
    echo "fn splash_tier(ch) {"
    echo "    if ((ch == 64) || (ch == 37) || (ch == 35)) { return 0; }   # @ % #"
    echo "    if ((ch == 42) || (ch == 43) || (ch == 61)) { return 1; }   # * + ="
    echo "    if ((ch == 45) || (ch == 58)) { return 2; }                 # - :"
    echo "    if (ch == 46) { return 3; }                                 # ."
    echo "    return -1;"
    echo "}"
    for W in $WIDTHS; do
        echo "fn _splash_${W}(i) {"
        awk '{ printf "    if (i == %d) { return \"%s\"; }\n", NR - 1, $0 }' "$tmp/rows.$W"
        echo "    return 0;"
        echo "}"
    done
} > "$OUT"
echo "gen-splash: $OUT <- $SRC (figure ${FW}x${FH}; widths: $WIDTHS)"
